class PsValueHolder {
  PsValueHolder(
      {required this.loginUserId,
      required this.userIdToVerify,
      required this.userNameToVerify,
      required this.userEmailToVerify,
      required this.userPasswordToVerify,
      required this.deviceToken,
      required this.notiSetting,
      required this.overAllTaxLabel,
      required this.overAllTaxValue,
      required this.shippingTaxLabel,
      required this.shopId,
      required this.messenger,
      required this.whatsApp,
      required this.phone,
      required this.minimumOrderAmount,
      required this.shippingTaxValue,
      required this.appInfoVersionNo,
      required this.appInfoForceUpdate,
      required this.appInfoForceUpdateTitle,
      required this.appInfoForceUpdateMsg,
      required this.startDate,
      required this.endDate,
      required this.lat,
      required this.lng,
        required this.postcode,
        required this.city,
        required this.country,
      required this.googlePlayStoreUrl,
      required this.appleAppStoreUrl,
      required this.defaultLanguageCode,
      required this.defaultLanguageCountryCode,
      required this.defaultLanguageName,
      required this.priceFormat,
      required this.dateFormat,
      required this.defaultOrderTime,
      required this.iOSAppStoreId,
      required this.isUseThumbnailAsPlaceholder,
      required this.isShowTokenId,
      required this.isShowSubCategory,
      required this.fbKey,
      required this.isShowAdmob,
      required this.defaultLoadingLimit,
      required this.categoryLoadingLimit,
      required this.collectionProductLoadingLimit,
      required this.discountProductLoadingLimit,
      required this.featureProductLoadingLimit,
      required this.latestProductLoadingLimit,
      required this.trendingProductLoadingLimit,
      required this.shopLoadingLimit,
      required this.showFacebookLogin,
      required this.showGoogleLogin,
      required this.showPhoneLogin,
      required this.showMainMenu,
      required this.showSpecialCollections,
      required this.showFeaturedItems,
      required this.isUserAlradyChoose,
      required this.isRazorSupportMultiCurrency,
      required this.defaultRazorCurrency,
      required this.defaultFlutterWaveCurrency,
      required this.paypalEnabled,
      required this.stripeEnabled,
      required this.codEnabled,
      required this.bankEnabled,
      required this.publishKey,
      required this.paystackKey,
      required this.isToShowIntroSlider,
      required this.paystackEnabled,
      required this.shippingId,
      required this.standardShippingEnable,
      required this.zoneShippingEnable,
      required this.noShippingEnable});
  String? loginUserId;
  String? userIdToVerify;
  String? userNameToVerify;
  String? userEmailToVerify;
  String? userPasswordToVerify;
  String? deviceToken;
  bool? isToShowIntroSlider;
  bool? isUserAlradyChoose;
  bool? notiSetting;
  String? overAllTaxLabel;
  String? overAllTaxValue;
  String? shippingTaxLabel;
  String? shopId;
  String? messenger;
  String? whatsApp;
  String? phone;
  String? minimumOrderAmount;
  String? shippingTaxValue;
  String? appInfoVersionNo;
  bool? appInfoForceUpdate;
  String? appInfoForceUpdateTitle;
  String? appInfoForceUpdateMsg;
  String? startDate;
  String? endDate;
  String? lat;
  String? lng;
  String? postcode;
  String? city;
  String? country;
  String? googlePlayStoreUrl;
  String? appleAppStoreUrl;
  String? defaultLanguageCode;
  String? defaultLanguageCountryCode;
  String? defaultLanguageName;
  String? priceFormat;
  String? dateFormat;
  String? defaultOrderTime;
  String? iOSAppStoreId;
  String? isUseThumbnailAsPlaceholder;
  String? isShowTokenId;
  String? isShowSubCategory;
  String? fbKey;
  String? isShowAdmob;
  String? defaultLoadingLimit;
  String? categoryLoadingLimit;
  String? collectionProductLoadingLimit;
  String? discountProductLoadingLimit;
  String? featureProductLoadingLimit;
  String? latestProductLoadingLimit;
  String? trendingProductLoadingLimit;
  String? shopLoadingLimit;
  String? showFacebookLogin;
  String? showGoogleLogin;
  String? showPhoneLogin;
  String? showMainMenu;
  String? showSpecialCollections;
  String? showFeaturedItems;
  String? paypalEnabled;
  String? stripeEnabled;
  String? codEnabled;
  String? bankEnabled;
  String? publishKey;
  String? paystackKey;
  String? paystackEnabled;
  String? shippingId;
  String? standardShippingEnable;
  String? zoneShippingEnable;
  String? noShippingEnable;
  String? isRazorSupportMultiCurrency;
  String? defaultRazorCurrency;
  String? defaultFlutterWaveCurrency;
}
