// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE4m6bpWz9j8Pg7KCR6MvuyJTcBBe9R2A',
    appId: '1:143475662683:web:9bce933560e12b9993447e',
    messagingSenderId: '143475662683',
    projectId: 'barkhana-4cd7e',
    authDomain: 'barkhana-4cd7e.firebaseapp.com',
    databaseURL: 'https://barkhana-4cd7e-default-rtdb.firebaseio.com',
    storageBucket: 'barkhana-4cd7e.appspot.com',
    measurementId: 'G-DBXCR0Z6WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8355QhaLalnSUmSdehP1xgrOQsXnr1qk',
    appId: '1:143475662683:android:ea47d20c0279a33b93447e',
    messagingSenderId: '143475662683',
    projectId: 'barkhana-4cd7e',
    databaseURL: 'https://barkhana-4cd7e-default-rtdb.firebaseio.com',
    storageBucket: 'barkhana-4cd7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCux-o84K2gbyLyIvjspgjpEnGZNZrH0PY',
    appId: '1:143475662683:ios:07b94e616542586993447e',
    messagingSenderId: '143475662683',
    projectId: 'barkhana-4cd7e',
    databaseURL: 'https://barkhana-4cd7e-default-rtdb.firebaseio.com',
    storageBucket: 'barkhana-4cd7e.appspot.com',
    androidClientId: '143475662683-13co5fomccvugnhs51dmard7slmrqvik.apps.googleusercontent.com',
    iosClientId: '143475662683-pb1go4mqtg3g12g5dgf2r0aed020janq.apps.googleusercontent.com',
    iosBundleId: 'com.its.Barkhana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCux-o84K2gbyLyIvjspgjpEnGZNZrH0PY',
    appId: '1:143475662683:ios:baf265488c85fc6993447e',
    messagingSenderId: '143475662683',
    projectId: 'barkhana-4cd7e',
    databaseURL: 'https://barkhana-4cd7e-default-rtdb.firebaseio.com',
    storageBucket: 'barkhana-4cd7e.appspot.com',
    androidClientId: '143475662683-13co5fomccvugnhs51dmard7slmrqvik.apps.googleusercontent.com',
    iosClientId: '143475662683-0cf33590g1npksos73lh7qvg1rtgotnn.apps.googleusercontent.com',
    iosBundleId: 'Barkhana.mobileSource.RunnerTests',
  );
}
